name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            website
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - run: cd website
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - run: cd website
      - name: Build website
        run: yarn build
      - run: cd website
      - name: Deploy to GitHub Pages 
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build